using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class StartingPlayerList : MonoBehaviour
{
    [HideInInspector] public List<DraftPick> InitialPlayers = new();

    private const int YEAR = 2025;
    private const float VERSION = 2.0f;

    public void LoadInitialPlayers()
    {
        if (!PlayerPrefs.HasKey(nameof(YEAR)) || PlayerPrefs.GetInt(nameof(YEAR)) != YEAR || !PlayerPrefs.HasKey(nameof(VERSION)) || PlayerPrefs.GetFloat(nameof(VERSION)) != VERSION)
        {
            PlayerPrefs.DeleteAll();
            PlayerPrefs.SetInt(nameof(YEAR), YEAR);
            PlayerPrefs.SetFloat(nameof(VERSION), VERSION);
            Debug.Log($"has tiers: {PlayerPrefs.HasKey("tiers")}");
            PlayerPrefs.Save();
        }

        CreatePlayer("Ja'marr Chase", ItemSlot.Position.WR, "CIN");
        CreatePlayer("Justin Jefferson", ItemSlot.Position.WR, "MIN");
        CreatePlayer("Brock Bowers", ItemSlot.Position.TE, "LV");
        CreatePlayer("Bijan Robinson", ItemSlot.Position.RB, "ATL");
        CreatePlayer("Jahmyr Gibbs", ItemSlot.Position.RB, "DET");
        CreatePlayer("Josh Allen", ItemSlot.Position.QB, "BUF");
        CreatePlayer("Malik Nabers", ItemSlot.Position.WR, "NYG");
        CreatePlayer("Ceedee Lamb", ItemSlot.Position.WR, "DAL");
        CreatePlayer("Jayden Daniels", ItemSlot.Position.QB, "WAS");
        CreatePlayer("Amon-Ra St. Brown", ItemSlot.Position.WR, "DET");
        CreatePlayer("Puka Nacua", ItemSlot.Position.WR, "LAR");
        CreatePlayer("Brian Thomas", ItemSlot.Position.WR, "JAX");
        CreatePlayer("Lamar Jackson", ItemSlot.Position.QB, "BAL");
        CreatePlayer("Trey McBride", ItemSlot.Position.TE, "ARI");
        CreatePlayer("Nico Collins", ItemSlot.Position.WR, "HOU");
        CreatePlayer("Ashton Jeanty", ItemSlot.Position.RB, "LV");
        CreatePlayer("Saquon Barkley", ItemSlot.Position.RB, "PHI");
        CreatePlayer("Drake London", ItemSlot.Position.WR, "ATL");
        CreatePlayer("Marvin Harrison", ItemSlot.Position.WR, "ARI");
        CreatePlayer("Ladd McConkey", ItemSlot.Position.WR, "LAC");
        CreatePlayer("Joe Burrow", ItemSlot.Position.QB, "CIN");
        CreatePlayer("De'von Achane", ItemSlot.Position.RB, "MIA");
        CreatePlayer("Omarion Hampton", ItemSlot.Position.RB, "LAC");
        CreatePlayer("Travis Hunter", ItemSlot.Position.WR, "JAX");
        CreatePlayer("Jalen Hurts", ItemSlot.Position.QB, "PHI");
        CreatePlayer("Garrett Wilson", ItemSlot.Position.WR, "NYJ");
        CreatePlayer("Tetairoa McMillan", ItemSlot.Position.WR, "CAR");
        CreatePlayer("Jaxon Smith-Njigba", ItemSlot.Position.WR, "SEA");
        CreatePlayer("A.J. Brown", ItemSlot.Position.WR, "PHI");
        CreatePlayer("Breece Hall", ItemSlot.Position.RB, "NYJ");
        CreatePlayer("Rashee Rice", ItemSlot.Position.WR, "KC");
        CreatePlayer("Sam LaPorta", ItemSlot.Position.TE, "DET");
        CreatePlayer("Bucky Irving", ItemSlot.Position.RB, "TB");
        CreatePlayer("Jonathan Taylor", ItemSlot.Position.RB, "IND");
        CreatePlayer("TreVeyon Henderson", ItemSlot.Position.RB, "NE");
        CreatePlayer("Kyren Williams", ItemSlot.Position.RB, "LAR");
        CreatePlayer("Tee Higgins", ItemSlot.Position.WR, "CIN");
        CreatePlayer("Rome Odunze", ItemSlot.Position.WR, "CHI");
        CreatePlayer("James Cook", ItemSlot.Position.RB, "BUF");
        CreatePlayer("Quinshon Judkins", ItemSlot.Position.RB, "CLE");
        CreatePlayer("Patrick Mahomes", ItemSlot.Position.QB, "KC");
        CreatePlayer("Josh Jacobs", ItemSlot.Position.RB, "GB");
        CreatePlayer("Christian McCaffrey", ItemSlot.Position.RB, "SF");
        CreatePlayer("Justin Herbert", ItemSlot.Position.QB, "LAC");
        CreatePlayer("Devonta Smith", ItemSlot.Position.WR, "PHI");
        CreatePlayer("Caleb Williams", ItemSlot.Position.QB, "CHI");
        CreatePlayer("Chase Brown", ItemSlot.Position.RB, "CIN");
        CreatePlayer("Drake Maye", ItemSlot.Position.QB, "NE");
        CreatePlayer("Chris Olave", ItemSlot.Position.WR, "NO");
        CreatePlayer("C.J. Stroud", ItemSlot.Position.QB, "HOU");
        CreatePlayer("Xavier Worthy", ItemSlot.Position.WR, "KC");
        CreatePlayer("Zay Flowers", ItemSlot.Position.WR, "BAL");
        CreatePlayer("Bo Nix", ItemSlot.Position.QB, "DEN");
        CreatePlayer("Emeka Egbuka", ItemSlot.Position.WR, "TB");
        CreatePlayer("DJ Moore", ItemSlot.Position.WR, "CHI");
        CreatePlayer("Kenneth Walker", ItemSlot.Position.RB, "SEA");
        CreatePlayer("Tyler Warren", ItemSlot.Position.TE, "IND");
        CreatePlayer("Derrick Henry", ItemSlot.Position.RB, "BAL");
        CreatePlayer("Jordan Addison", ItemSlot.Position.WR, "MIN");
        CreatePlayer("T.J. Hockenson", ItemSlot.Position.TE, "MIN");
        CreatePlayer("Terry McLaurin", ItemSlot.Position.WR, "WAS");
        CreatePlayer("Jaylen Waddle", ItemSlot.Position.WR, "MIA");
        CreatePlayer("Kaleb Johnson", ItemSlot.Position.RB, "PIT");
        CreatePlayer("Jordan Love", ItemSlot.Position.QB, "GB");
        CreatePlayer("Colston Loveland", ItemSlot.Position.TE, "CHI");
        CreatePlayer("Tyreek Hill", ItemSlot.Position.WR, "MIA");
        CreatePlayer("George Pickens", ItemSlot.Position.WR, "PIT");
        CreatePlayer("RJ Harvey", ItemSlot.Position.RB, "DEN");
        CreatePlayer("George Kittle", ItemSlot.Position.TE, "SF");
        CreatePlayer("Matthew Golden", ItemSlot.Position.WR, "GB");
        CreatePlayer("Chuba Hubbard", ItemSlot.Position.RB, "CAR");
        CreatePlayer("DK Metcalf", ItemSlot.Position.WR, "PIT");
        CreatePlayer("Jameson Williams", ItemSlot.Position.WR, "DET");
        CreatePlayer("Brandon Aiyuk", ItemSlot.Position.WR, "SF");
        CreatePlayer("Joe Mixon", ItemSlot.Position.RB, "HOU");
        CreatePlayer("Kyler Murray", ItemSlot.Position.QB, "ARI");
        CreatePlayer("Dalton Kincaid", ItemSlot.Position.TE, "BUF");
        CreatePlayer("Mark Andrews", ItemSlot.Position.TE, "BAL");
        CreatePlayer("Jerry Jeudy", ItemSlot.Position.WR, "CLE");
        CreatePlayer("Mike Evans", ItemSlot.Position.WR, "TB");
        CreatePlayer("Baker Mayfield", ItemSlot.Position.QB, "TB");
        CreatePlayer("Luther Burden", ItemSlot.Position.WR, "CHI");
        CreatePlayer("Jayden Reed", ItemSlot.Position.WR, "GB");
        CreatePlayer("Tre Harris", ItemSlot.Position.WR, "LAC");
        CreatePlayer("David Montgomery", ItemSlot.Position.RB, "DET");
        CreatePlayer("Tyrone Tracy", ItemSlot.Position.RB, "NYG");
        CreatePlayer("Alvin Kamara", ItemSlot.Position.RB, "NO");
        CreatePlayer("Michael Penix", ItemSlot.Position.QB, "ATL");
        CreatePlayer("Jalen McMillan", ItemSlot.Position.WR, "TB");
        CreatePlayer("Kyle Pitts", ItemSlot.Position.TE, "ATL");
        CreatePlayer("JJ McCarthy", ItemSlot.Position.QB, "MIN");
        CreatePlayer("Brock Purdy", ItemSlot.Position.QB, "SF");
        CreatePlayer("Josh Downs", ItemSlot.Position.WR, "IND");
        CreatePlayer("Cam Ward", ItemSlot.Position.QB, "TEN");
        CreatePlayer("David Njoku", ItemSlot.Position.TE, "CLE");
        CreatePlayer("Chris Godwin", ItemSlot.Position.WR, "TB");
        CreatePlayer("Travis Etienne", ItemSlot.Position.RB, "JAX");
        CreatePlayer("Jayden Higgins", ItemSlot.Position.WR, "HOU");
        CreatePlayer("Isiah Pacheco", ItemSlot.Position.RB, "KC");
        CreatePlayer("Ricky Pearsall", ItemSlot.Position.WR, "SF");
        CreatePlayer("Tucker Kraft", ItemSlot.Position.TE, "GB");
        CreatePlayer("Michael Pittman", ItemSlot.Position.WR, "IND");
        CreatePlayer("Keon Coleman", ItemSlot.Position.WR, "BUF");
        CreatePlayer("Trevor Lawrence", ItemSlot.Position.QB, "JAX");
        CreatePlayer("Courtland Sutton", ItemSlot.Position.WR, "DEN");
        CreatePlayer("Cam Skattebo", ItemSlot.Position.RB, "NYG");
        CreatePlayer("Khalil Shakir", ItemSlot.Position.WR, "BUF");
        CreatePlayer("Brian Robinson", ItemSlot.Position.RB, "WAS");
        CreatePlayer("James Conner", ItemSlot.Position.RB, "ARI");
        CreatePlayer("D'Andre Swift", ItemSlot.Position.RB, "CHI");
        CreatePlayer("Davante Adams", ItemSlot.Position.WR, "LAR");
        CreatePlayer("Zach Charbonnet", ItemSlot.Position.RB, "SEA");
        CreatePlayer("Bryce Young", ItemSlot.Position.QB, "CAR");
        CreatePlayer("Jake Ferguson", ItemSlot.Position.TE, "DAL");
        CreatePlayer("Jared Goff", ItemSlot.Position.QB, "DET");
        CreatePlayer("Rhamondre Stevenson", ItemSlot.Position.RB, "NE");
        CreatePlayer("Isaiah Likely", ItemSlot.Position.TE, "BAL");
        CreatePlayer("Jonnu Smith", ItemSlot.Position.TE, "MIA");
        CreatePlayer("Anthony Richardson", ItemSlot.Position.QB, "IND");
        CreatePlayer("Trey Benson", ItemSlot.Position.RB, "ARI");
        CreatePlayer("Najee Harris", ItemSlot.Position.RB, "LAC");
        CreatePlayer("Tony Pollard", ItemSlot.Position.RB, "TEN");
        CreatePlayer("Jack Bech", ItemSlot.Position.WR, "LV");
        CreatePlayer("Dak Prescott", ItemSlot.Position.QB, "DAL");
        CreatePlayer("Deebo Samuel", ItemSlot.Position.WR, "WAS");
        CreatePlayer("Jaylin Noel", ItemSlot.Position.WR, "HOU");
        CreatePlayer("Jakobi Meyers", ItemSlot.Position.WR, "LV");
        CreatePlayer("JK Dobbins", ItemSlot.Position.RB, "FA");
        CreatePlayer("Cade Otton", ItemSlot.Position.TE, "TB");
        CreatePlayer("Xavier Legette", ItemSlot.Position.WR, "CAR");
        CreatePlayer("Evan Engram", ItemSlot.Position.TE, "DEN");
        CreatePlayer("Cooper Kupp", ItemSlot.Position.WR, "SEA");
        CreatePlayer("Tua Tagovailoa", ItemSlot.Position.QB, "MIA");
        CreatePlayer("Tyjae Spears", ItemSlot.Position.RB, "TEN");
        CreatePlayer("Mason Taylor", ItemSlot.Position.TE, "NYJ");
        CreatePlayer("Travis Kelce", ItemSlot.Position.TE, "KC");
        CreatePlayer("Pat Freiermuth", ItemSlot.Position.TE, "PIT");
        CreatePlayer("Cole Kmet", ItemSlot.Position.TE, "CHI");
        CreatePlayer("Calvin Ridley", ItemSlot.Position.WR, "TEN");
        CreatePlayer("Bhayshul Tuten", ItemSlot.Position.RB, "JAX");
        CreatePlayer("Sam Darnold", ItemSlot.Position.QB, "SEA");
        CreatePlayer("Dylan Sampson", ItemSlot.Position.RB, "CLE");
        CreatePlayer("Aaron Jones", ItemSlot.Position.RB, "MIN");
        CreatePlayer("Justin Fields", ItemSlot.Position.QB, "NYJ");
        CreatePlayer("Rachaad White", ItemSlot.Position.RB, "TB");
        CreatePlayer("Rashid Shaheed", ItemSlot.Position.WR, "NO");
        CreatePlayer("Tank Bigsby", ItemSlot.Position.RB, "JAX");
        CreatePlayer("Tank Dell", ItemSlot.Position.WR, "HOU");
        CreatePlayer("Elijah Arroyo", ItemSlot.Position.TE, "SEA");
        CreatePlayer("Jauan Jennings", ItemSlot.Position.WR, "SF");
        CreatePlayer("Jaylen Warren", ItemSlot.Position.RB, "PIT");
        CreatePlayer("Marvin Mims", ItemSlot.Position.WR, "DEN");
        CreatePlayer("Jonathon Brooks", ItemSlot.Position.RB, "CAR");
        CreatePlayer("Darnell Mooney", ItemSlot.Position.WR, "ATL");
        CreatePlayer("Dallas Goedert", ItemSlot.Position.TE, "PHI");
        CreatePlayer("Devin Neal", ItemSlot.Position.RB, "NO");
        CreatePlayer("Ben Sinnott", ItemSlot.Position.TE, "WAS");
        CreatePlayer("Stefon Diggs", ItemSlot.Position.WR, "NE");
        CreatePlayer("Ja'Tavion Sanders", ItemSlot.Position.TE, "CAR");
        CreatePlayer("Quentin Johnston", ItemSlot.Position.WR, "LAC");
        CreatePlayer("Terrance Ferguson", ItemSlot.Position.TE, "LAR");
        CreatePlayer("Jalen Coker", ItemSlot.Position.WR, "CAR");
        CreatePlayer("Blake Corum", ItemSlot.Position.RB, "LAR");
        CreatePlayer("Cedric Tillman", ItemSlot.Position.WR, "CLE");
        CreatePlayer("Jaylen Wright", ItemSlot.Position.RB, "MIA");
        CreatePlayer("Harold Fannin", ItemSlot.Position.TE, "CLE");
        CreatePlayer("Braelon Allen", ItemSlot.Position.RB, "NYJ");
        CreatePlayer("Jalen Milroe", ItemSlot.Position.QB, "SEA");
        CreatePlayer("Rashod Bateman", ItemSlot.Position.WR, "BAL");
        CreatePlayer("Jaydon Blue", ItemSlot.Position.RB, "DAL");
        CreatePlayer("Javonte Williams", ItemSlot.Position.RB, "DAL");
        CreatePlayer("Romeo Doubs", ItemSlot.Position.WR, "GB");
        CreatePlayer("Hollywood Brown", ItemSlot.Position.WR, "KC");
        CreatePlayer("Christian Kirk", ItemSlot.Position.WR, "HOU");
        CreatePlayer("Rico Dowdle", ItemSlot.Position.RB, "CAR");
        CreatePlayer("Adonai Mitchell", ItemSlot.Position.WR, "IND");
        CreatePlayer("Wan'Dale Robinson", ItemSlot.Position.WR, "NYG");
        CreatePlayer("Jalen Royals", ItemSlot.Position.WR, "KC");
        CreatePlayer("Theo Johnson", ItemSlot.Position.TE, "NYG");
        CreatePlayer("Amari Cooper", ItemSlot.Position.WR, "FA");
        CreatePlayer("Chig Okonkwo", ItemSlot.Position.TE, "TEN");
        CreatePlayer("Demario Douglas", ItemSlot.Position.WR, "NE");
        CreatePlayer("Ray Davis", ItemSlot.Position.RB, "BUF");
        CreatePlayer("Isaac Guerendo", ItemSlot.Position.RB, "SF");
        CreatePlayer("Jerome Ford", ItemSlot.Position.RB, "CLE");
        CreatePlayer("Troy Franklin", ItemSlot.Position.WR, "DEN");
        CreatePlayer("Geno Smith", ItemSlot.Position.QB, "LV");
        CreatePlayer("Tyler Allgeier", ItemSlot.Position.RB, "ATL");
        CreatePlayer("Matthew Stafford", ItemSlot.Position.QB, "LAR");
        CreatePlayer("Dalton Schultz", ItemSlot.Position.TE, "HOU");
        CreatePlayer("Kendre Miller", ItemSlot.Position.RB, "NO");
        CreatePlayer("Keenan Allen", ItemSlot.Position.WR, "FA");
        CreatePlayer("Ollie Gordon", ItemSlot.Position.RB, "MIA");
        CreatePlayer("Christian Watson", ItemSlot.Position.WR, "GB");
        CreatePlayer("Elic Ayomanor", ItemSlot.Position.WR, "TEN");
        CreatePlayer("Dontayvion Wicks", ItemSlot.Position.WR, "GB");
        CreatePlayer("Marshawn Lloyd", ItemSlot.Position.RB, "GB");
        CreatePlayer("Hunter Henry", ItemSlot.Position.TE, "NE");
        CreatePlayer("Noah Grey", ItemSlot.Position.TE, "KC");
        CreatePlayer("Audric Estime", ItemSlot.Position.RB, "DEN");
        CreatePlayer("Jordan Mason", ItemSlot.Position.RB, "MIN");
        CreatePlayer("Jordan Whittington", ItemSlot.Position.WR, "LAR");
        CreatePlayer("Nick Chubb", ItemSlot.Position.RB, "FA");
        CreatePlayer("Austin Ekeler", ItemSlot.Position.RB, "WAS");
        CreatePlayer("Brenton Strange", ItemSlot.Position.TE, "JAX");
        CreatePlayer("DJ Giddens", ItemSlot.Position.RB, "IND");
        CreatePlayer("Zach Ertz", ItemSlot.Position.TE, "WAS");
        CreatePlayer("Jaxson Dart", ItemSlot.Position.QB, "NYG");
        CreatePlayer("Andrei Iosivas", ItemSlot.Position.WR, "CIN");
        CreatePlayer("Malik Washington", ItemSlot.Position.WR, "MIA");
        CreatePlayer("Roschon Johnson", ItemSlot.Position.RB, "CHI");
        CreatePlayer("Ja'Lynn Polk", ItemSlot.Position.WR, "NE");
        CreatePlayer("Mike Gesicki", ItemSlot.Position.TE, "CIN");
        CreatePlayer("Diontae Johnson", ItemSlot.Position.WR, "CLE");
        CreatePlayer("Damien Martinez", ItemSlot.Position.RB, "SEA");
        CreatePlayer("Adam Thielen", ItemSlot.Position.WR, "CAR");
        CreatePlayer("Alec Pierce", ItemSlot.Position.WR, "IND");
        CreatePlayer("Kayshon Boutte", ItemSlot.Position.WR, "NE");
        CreatePlayer("Roman Wilson", ItemSlot.Position.WR, "PIT");
        CreatePlayer("Michael Mayer", ItemSlot.Position.TE, "LV");
        CreatePlayer("Michael Wilson", ItemSlot.Position.WR, "ARI");
        CreatePlayer("Keaton Mitchell", ItemSlot.Position.RB, "BAL");
        CreatePlayer("Trevor Etienne", ItemSlot.Position.RB, "CAR");
    }

    void CreatePlayer(string name, ItemSlot.Position position, string teamAbrev)
    {
        string[] split = name.Split(' ');
        if (name == "Amon-Ra St. Brown")
        {
            split[0] = "Amon-Ra";
            split[1] = "St. Brown";
        }

        MetaData metaData = new MetaData() { first_name = split[0], last_name = split[1], team = teamAbrev, position = position.ToString() };
        DraftPick pc = new() { metadata = metaData, adpRanking = InitialPlayers.Count + 1 };
        InitialPlayers.Add(pc);
    }
}
