using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class StartingPlayerList : MonoBehaviour
{
    [HideInInspector] public List<DraftPick> InitialPlayers = new();

    public void LoadInitialPlayers()
    {
        CreatePlayer("Christian McCaffrey", ItemSlot.Position.RB, "SF");
        CreatePlayer("Ceedee Lamb", ItemSlot.Position.WR, "DAL");
        CreatePlayer("Tyreek Hill", ItemSlot.Position.WR, "MIA");
        CreatePlayer("Justin Jefferson", ItemSlot.Position.WR, "MIN");
        CreatePlayer("Ja'marr Chase", ItemSlot.Position.WR, "CIN");
        CreatePlayer("Amon-Ra St. Brown", ItemSlot.Position.WR, "DET");
        CreatePlayer("Bijan Robinson", ItemSlot.Position.RB, "ATL");
        CreatePlayer("Breece Hall", ItemSlot.Position.RB, "NYJ");
        CreatePlayer("AJ Brown", ItemSlot.Position.WR, "PHI");
        CreatePlayer("Puka Nacua", ItemSlot.Position.WR, "LAR");
        CreatePlayer("Jahmyr Gibbs", ItemSlot.Position.RB, "DET");
        CreatePlayer("Garrett Wilson", ItemSlot.Position.WR, "NYJ");
        CreatePlayer("Jonathan Taylor", ItemSlot.Position.RB, "IND");
        CreatePlayer("Saquon Barkley", ItemSlot.Position.RB, "PHI");
        CreatePlayer("Marvin Harrison", ItemSlot.Position.WR, "ARI");
        CreatePlayer("Kyren Williams", ItemSlot.Position.RB, "LAR");
        CreatePlayer("Davante Adams", ItemSlot.Position.WR, "LV");
        CreatePlayer("Drake London", ItemSlot.Position.WR, "ATL");
        CreatePlayer("Sam LaPorta", ItemSlot.Position.TE, "DET");
        CreatePlayer("Chris Olave", ItemSlot.Position.WR, "NO");
        CreatePlayer("Travis Etienne", ItemSlot.Position.RB, "JAX");
        CreatePlayer("Josh Allen", ItemSlot.Position.QB, "BUF");
        CreatePlayer("Brandon Aiyuk", ItemSlot.Position.WR, "SF");
        CreatePlayer("De'von Achane", ItemSlot.Position.RB, "MIA");
        CreatePlayer("Travis Kelce", ItemSlot.Position.TE, "KC");
        CreatePlayer("Derrick Henry", ItemSlot.Position.RB, "BAL");
        CreatePlayer("Josh Jacobs", ItemSlot.Position.RB, "GB");
        CreatePlayer("Mike Evans", ItemSlot.Position.WR, "TB");
        CreatePlayer("Nico Collins", ItemSlot.Position.WR, "HOU");
        CreatePlayer("Stefon Diggs", ItemSlot.Position.WR, "HOU");
        CreatePlayer("Isiah Pacheco", ItemSlot.Position.RB, "KC");
        CreatePlayer("Deebo Samuel", ItemSlot.Position.WR, "SF");
        CreatePlayer("Jalen Hurts", ItemSlot.Position.QB, "PHI");
        CreatePlayer("Patrick Mahomes", ItemSlot.Position.QB, "KC");
        CreatePlayer("DJ Moore", ItemSlot.Position.WR, "CHI");
        CreatePlayer("Jaylen Waddle", ItemSlot.Position.WR, "MIA");
        CreatePlayer("Michael Pittman", ItemSlot.Position.WR, "IND");
        CreatePlayer("Lamar Jackson", ItemSlot.Position.QB, "BAL");
        CreatePlayer("Rachaad White", ItemSlot.Position.RB, "TB");
        CreatePlayer("Malik Nabers", ItemSlot.Position.WR, "NYG");
        CreatePlayer("Cooper Kupp", ItemSlot.Position.WR, "LAR");
        CreatePlayer("CJ Stroud", ItemSlot.Position.QB, "HOU");
        CreatePlayer("Trey McBride", ItemSlot.Position.TE, "ARI");
        CreatePlayer("James Cook", ItemSlot.Position.RB, "BUF");
        CreatePlayer("DK Metcalf", ItemSlot.Position.WR, "SEA");
        CreatePlayer("Devonta Smith", ItemSlot.Position.WR, "PHI");
        CreatePlayer("Mark Andrews", ItemSlot.Position.TE, "BAL");
        CreatePlayer("Joe Mixon", ItemSlot.Position.RB, "HOU");
        CreatePlayer("Dalton Kincaid", ItemSlot.Position.TE, "BUF");
        CreatePlayer("Alvin Kamara", ItemSlot.Position.RB, "NO");
        CreatePlayer("Zay Flowers", ItemSlot.Position.WR, "BAL");
        CreatePlayer("Kenneth Walker", ItemSlot.Position.RB, "SEA");
        CreatePlayer("Tank Dell", ItemSlot.Position.WR, "HOU");
        CreatePlayer("George Pickens", ItemSlot.Position.WR, "PIT");
        CreatePlayer("Kyle Pitts", ItemSlot.Position.TE, "ATL");
        CreatePlayer("Tee Higgins", ItemSlot.Position.WR, "CIN");
        CreatePlayer("Amari Cooper", ItemSlot.Position.WR, "CLE");
        CreatePlayer("Anthony Richardson", ItemSlot.Position.QB, "IND");
        CreatePlayer("Keenan Allen", ItemSlot.Position.WR, "CHI");
        CreatePlayer("George Kittle", ItemSlot.Position.TE, "SF");
        CreatePlayer("Aaron Jones", ItemSlot.Position.RB, "MIN");
        CreatePlayer("James Conner", ItemSlot.Position.RB, "ARI");
        CreatePlayer("Christian Kirk", ItemSlot.Position.WR, "JAX");
        CreatePlayer("Joe Burrow", ItemSlot.Position.QB, "CIN");
        CreatePlayer("David Montgomery", ItemSlot.Position.RB, "DET");
        CreatePlayer("D'Andre Swift", ItemSlot.Position.RB, "CHI");
        CreatePlayer("Evan Engram", ItemSlot.Position.TE, "JAX");
        CreatePlayer("Terry McLaurin", ItemSlot.Position.WR, "WAS");
        CreatePlayer("Rome Odunze", ItemSlot.Position.WR, "CHI");
        CreatePlayer("Rhamondre Stevenson", ItemSlot.Position.RB, "NE");
        CreatePlayer("Rashee Rice", ItemSlot.Position.WR, "KC");
        CreatePlayer("Jayden Reed", ItemSlot.Position.WR, "GB");
        CreatePlayer("Jordan Addison", ItemSlot.Position.WR, "MIN");
        CreatePlayer("Dak Prescott", ItemSlot.Position.QB, "DAL");
        CreatePlayer("Chris Godwin", ItemSlot.Position.WR, "TB");
        CreatePlayer("Xavier Worthy", ItemSlot.Position.WR, "KC");
        CreatePlayer("Brock Bowers", ItemSlot.Position.TE, "LV");
        CreatePlayer("Najee Harris", ItemSlot.Position.RB, "PIT");
        CreatePlayer("Calvin Ridley", ItemSlot.Position.WR, "TEN");
        CreatePlayer("Tony Pollard", ItemSlot.Position.RB, "TEN");
        CreatePlayer("Zamir White", ItemSlot.Position.RB, "LV");
        CreatePlayer("Hollywood Brown", ItemSlot.Position.WR, "KC");
        CreatePlayer("Kyler Murray", ItemSlot.Position.QB, "ARI");
        CreatePlayer("Raheem Mostert", ItemSlot.Position.RB, "MIA");
        CreatePlayer("David Njoku", ItemSlot.Position.TE, "CLE");
        CreatePlayer("Jordan Love", ItemSlot.Position.QB, "GB");
        CreatePlayer("Jake Ferguson", ItemSlot.Position.TE, "DAL");
        CreatePlayer("Ladd McConkey", ItemSlot.Position.WR, "LAC");
        CreatePlayer("DeAndre Hopkins", ItemSlot.Position.WR, "TEN");
        CreatePlayer("Nick Chubb", ItemSlot.Position.RB, "CLE");
        CreatePlayer("Jonathan Brooks", ItemSlot.Position.RB, "CAR");
        CreatePlayer("Javonte Williams", ItemSlot.Position.RB, "DEN");
        CreatePlayer("Diontae Johnson", ItemSlot.Position.WR, "CAR");
        CreatePlayer("Zack Moss", ItemSlot.Position.RB, "CIN");
        CreatePlayer("Austin Ekeler", ItemSlot.Position.RB, "WAS");
        CreatePlayer("Keon Coleman", ItemSlot.Position.WR, "BUF");
        CreatePlayer("Brian Thomas Jr", ItemSlot.Position.WR, "JAX");
        CreatePlayer("Jaylen Warren", ItemSlot.Position.RB, "PIT");
        CreatePlayer("Brock Purdy", ItemSlot.Position.QB, "SF");
        CreatePlayer("Jaxon Smith-Njigba", ItemSlot.Position.WR, "SEA");
        CreatePlayer("Christian Watson", ItemSlot.Position.WR, "GB");
        CreatePlayer("Caleb Williams", ItemSlot.Position.QB, "CHI");
        CreatePlayer("Devin Singletary", ItemSlot.Position.RB, "NYG");
        CreatePlayer("Dallas Goedert", ItemSlot.Position.TE, "PHI");
        CreatePlayer("TJ Hockenson", ItemSlot.Position.TE, "MIN");
        CreatePlayer("Trey Benson", ItemSlot.Position.RB, "ARI");
        CreatePlayer("Tua Tagovailoa", ItemSlot.Position.QB, "MIA");
        CreatePlayer("Dalton Schultz", ItemSlot.Position.TE, "HOU");
        CreatePlayer("Tyjae Spears", ItemSlot.Position.RB, "TEN");
        CreatePlayer("Jameson Williams", ItemSlot.Position.WR, "DET");
        CreatePlayer("Brian Robinson", ItemSlot.Position.RB, "WAS");
        CreatePlayer("Jared Goff", ItemSlot.Position.QB, "DET");
        CreatePlayer("Gus Edwards", ItemSlot.Position.RB, "LAC");
        CreatePlayer("Ezekiel Elliot", ItemSlot.Position.RB, "DAL");
        CreatePlayer("Jayden Daniels", ItemSlot.Position.QB, "WAS");
        CreatePlayer("Cortland Sutton", ItemSlot.Position.WR, "DEN");
        CreatePlayer("Blake Corum", ItemSlot.Position.RB, "LAR");
        CreatePlayer("Romeo Doubs", ItemSlot.Position.WR, "GB");
        CreatePlayer("Curtis Samuel", ItemSlot.Position.WR, "WAS");
        CreatePlayer("Justin Herbert", ItemSlot.Position.QB, "LAC");
        CreatePlayer("Tyler Lockett", ItemSlot.Position.WR, "SEA");
        CreatePlayer("Chase Brown", ItemSlot.Position.RB, "CIN");
        CreatePlayer("Cole Kmet", ItemSlot.Position.TE, "CHI");
        CreatePlayer("Adonai Mitchell", ItemSlot.Position.WR, "IND");
        CreatePlayer("Jerome Ford", ItemSlot.Position.RB, "CLE");
        CreatePlayer("Pat Freiermuth", ItemSlot.Position.TE, "PIT");
        CreatePlayer("Trevor Lawrence", ItemSlot.Position.QB, "JAX");
        CreatePlayer("Khalil Shakir", ItemSlot.Position.WR, "BUF");
        CreatePlayer("Jakobi Meyers", ItemSlot.Position.WR, "LV");
        CreatePlayer("Zach Charbonnet", ItemSlot.Position.RB, "SEA");
        CreatePlayer("Xavier Legette", ItemSlot.Position.WR, "CAR");
        CreatePlayer("Luke Musgrave", ItemSlot.Position.TE, "GB");
        CreatePlayer("Mike Williams", ItemSlot.Position.WR, "NYJ");
        CreatePlayer("Jerry Jeudy", ItemSlot.Position.WR, "CLE");
        CreatePlayer("Kirk Cousins", ItemSlot.Position.QB, "ATL");
        CreatePlayer("Chuba Hubbard", ItemSlot.Position.RB, "CAR");
        CreatePlayer("Matthew Stafford", ItemSlot.Position.QB, "LAR");
        CreatePlayer("Jaylen Wright", ItemSlot.Position.RB, "MIA");
        CreatePlayer("Rashid Shaheed", ItemSlot.Position.WR, "NO");
        CreatePlayer("Josh Palmer", ItemSlot.Position.WR, "LAC");
        CreatePlayer("Aaron Rodgers", ItemSlot.Position.QB, "NYJ");
        CreatePlayer("Josh Downs", ItemSlot.Position.WR, "IND");
        CreatePlayer("JK Dobbins", ItemSlot.Position.RB, "LAC");
        CreatePlayer("Kendre Miller", ItemSlot.Position.RB, "NO");
        CreatePlayer("Rico Dowdle", ItemSlot.Position.RB, "DAL");
        CreatePlayer("Gabe Davis", ItemSlot.Position.WR, "JAX");
        CreatePlayer("Ben Sinnott", ItemSlot.Position.TE, "WAS");
        CreatePlayer("Troy Franklin", ItemSlot.Position.WR, "DEN");
        CreatePlayer("Justin Tucker", ItemSlot.Position.OTHER, "BAL");
        CreatePlayer("Harrison Butker", ItemSlot.Position.OTHER, "KC");
        CreatePlayer("Brandon Aubrey", ItemSlot.Position.OTHER, "DAL");
        CreatePlayer("49ers Defense", ItemSlot.Position.OTHER, "SF");
        CreatePlayer("Evan McPherson", ItemSlot.Position.OTHER, "CIN");
        CreatePlayer("Jake Elliot", ItemSlot.Position.OTHER, "PHI");
        CreatePlayer("Younghoe Koo", ItemSlot.Position.OTHER, "ATL");
        CreatePlayer("Tyler Bass", ItemSlot.Position.OTHER, "BUF");
        CreatePlayer("Brandin Cooks", ItemSlot.Position.WR, "DAL");
        CreatePlayer("Ty Chandler", ItemSlot.Position.RB, "MIN");
        CreatePlayer("Baker Mayfield", ItemSlot.Position.QB, "TB");
        CreatePlayer("Cade Otton", ItemSlot.Position.TE, "TB");
        CreatePlayer("Jets Defense", ItemSlot.Position.OTHER, "NYJ");
        CreatePlayer("Marshawn Lloyd", ItemSlot.Position.RB, "GB");
        CreatePlayer("Ja'lynn Polk", ItemSlot.Position.WR, "NE");
        CreatePlayer("Dontayvion Wicks", ItemSlot.Position.WR, "GB");
        CreatePlayer("Jahan Dotson", ItemSlot.Position.WR, "WAS");
        CreatePlayer("Ricky Pearsall", ItemSlot.Position.WR, "SF");
        CreatePlayer("Tyler Allgeier", ItemSlot.Position.RB, "ATL");
        CreatePlayer("Antonio Gibson", ItemSlot.Position.RB, "NE");
        CreatePlayer("Deshaun Watson", ItemSlot.Position.QB, "CLE");
        CreatePlayer("Jaleel McLaughlin", ItemSlot.Position.RB, "DEN");
        CreatePlayer("Quentin Johnston", ItemSlot.Position.WR, "LAC");
        CreatePlayer("Kimani Vidal", ItemSlot.Position.RB, "LAC");
        CreatePlayer("Taysom Hill", ItemSlot.Position.TE, "NO");
        CreatePlayer("Adam Thielen", ItemSlot.Position.WR, "CAR");
        CreatePlayer("Isaiah Likely", ItemSlot.Position.TE, "BAL");
        CreatePlayer("Hunter Henry", ItemSlot.Position.TE, "NE");
        CreatePlayer("Roman Wilson", ItemSlot.Position.WR, "PIT");
        CreatePlayer("Demario Douglas", ItemSlot.Position.WR, "NE");
        CreatePlayer("Tyrone Tracy", ItemSlot.Position.RB, "NYG");
        CreatePlayer("Darnell Mooney", ItemSlot.Position.WR, "ATL");
        CreatePlayer("Ray Davis", ItemSlot.Position.RB, "BUF");
        CreatePlayer("Chigoziem Okonkwo", ItemSlot.Position.TE, "TEN");
        CreatePlayer("Jermaine Burton", ItemSlot.Position.WR, "CIN");
        CreatePlayer("Jake Moody", ItemSlot.Position.OTHER, "SF");
        CreatePlayer("Cameron Dicker", ItemSlot.Position.OTHER, "LAC");
        CreatePlayer("Ka'imi Fairbairn", ItemSlot.Position.OTHER, "HOU");
        CreatePlayer("Cowboys Defense", ItemSlot.Position.OTHER, "DAL");
        CreatePlayer("Jason Sanders", ItemSlot.Position.OTHER, "MIA");
        CreatePlayer("Daniel Carlson", ItemSlot.Position.OTHER, "LV");
        CreatePlayer("Will Levis", ItemSlot.Position.QB, "TEN");
        CreatePlayer("Geno Smith", ItemSlot.Position.QB, "SEA");
        CreatePlayer("Ravens Defense", ItemSlot.Position.OTHER, "BAL");
        CreatePlayer("Tyler Conklin", ItemSlot.Position.TE, "NYJ");
        CreatePlayer("Elijah Mitchell", ItemSlot.Position.RB, "SF");
        CreatePlayer("Malachi Corley", ItemSlot.Position.WR, "NYJ");
        CreatePlayer("Bucky Irving", ItemSlot.Position.RB, "TB");
        CreatePlayer("Rashod Bateman", ItemSlot.Position.WR, "BAL");
    }

    void CreatePlayer(string name, ItemSlot.Position position, string teamAbrev)
    {
        string[] split = name.Split(' ');
        MetaData metaData = new MetaData() { first_name = split[0], last_name = split[1], team = teamAbrev, position = position.ToString() };
        DraftPick pc = new() { metadata = metaData, adpRanking = InitialPlayers.Count + 1 };
        InitialPlayers.Add(pc);
    }
}
